In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('IMDB Dataset.csv')

In [3]:
data.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [5]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

NLP

TEXT PREPROCESSING USING NLP

In [6]:
%pip install nltk

Requirement already satisfied: nltk in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\praka\anaconda3\envs\smart_document_understanding\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import nltk
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [8]:
texts = data['review'].head(3).tolist()
texts

["One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",
 'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.',
 'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.']

Lowercasing

In [9]:
texts = [t.lower() for t in texts]
texts

["one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",
 'a wonderful little production. <br /><br />the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. <br /><br />the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.',
 'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.<br /><br />this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.']

Removing Punctuation

In [10]:
def remove_punctuation(text):
    return text.translate(str.maketrans('' , '', string.punctuation))
texts = [remove_punctuation(t) for t in texts]
texts

['one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with mebr br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordbr br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side',
 'a wonderful little production br br the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done',
 'i thought this was a wonderful way to spend time on a too hot summer weekend sitting in the air conditioned theater and watching a lighthearted comedy the plot is simplistic but the dialogue is witty and the characters are likable even the well bread suspected serial killer while some may be disappointed when they realize this is not match point 2 risk addiction i thought it was proof that woody allen is still fully in control of the style many of us have grown to lovebr br this was the most id laughed at one of woodys comedies in years dare i say a decade while ive never been impressed with scarlet johanson in this she managed to tone down her sexy image and jumped right into a average but spirited young womanbr br this may not be the crown jewel of his career but it was wittier than devil wears prada and more interesting than superman a great comedy to go see with friends']

Tokenize

In [11]:
tokens = [word_tokenize(t) for t in texts]
tokens

[['one',
  'of',
  'the',
  'other',
  'reviewers',
  'has',
  'mentioned',
  'that',
  'after',
  'watching',
  'just',
  '1',
  'oz',
  'episode',
  'youll',
  'be',
  'hooked',
  'they',
  'are',
  'right',
  'as',
  'this',
  'is',
  'exactly',
  'what',
  'happened',
  'with',
  'mebr',
  'br',
  'the',
  'first',
  'thing',
  'that',
  'struck',
  'me',
  'about',
  'oz',
  'was',
  'its',
  'brutality',
  'and',
  'unflinching',
  'scenes',
  'of',
  'violence',
  'which',
  'set',
  'in',
  'right',
  'from',
  'the',
  'word',
  'go',
  'trust',
  'me',
  'this',
  'is',
  'not',
  'a',
  'show',
  'for',
  'the',
  'faint',
  'hearted',
  'or',
  'timid',
  'this',
  'show',
  'pulls',
  'no',
  'punches',
  'with',
  'regards',
  'to',
  'drugs',
  'sex',
  'or',
  'violence',
  'its',
  'is',
  'hardcore',
  'in',
  'the',
  'classic',
  'use',
  'of',
  'the',
  'wordbr',
  'br',
  'it',
  'is',
  'called',
  'oz',
  'as',
  'that',
  'is',
  'the',
  'nickname',
  'given',
  'to',
  'the',
  'oswald',
  'maximum',
  'security',
  'state',
  'penitentary',
  'it',
  'focuses',
  'mainly',
  'on',
  'emerald',
  'city',
  'an',
  'experimental',
  'section',
  'of',
  'the',
  'prison',
  'where',
  'all',
  'the',
  'cells',
  'have',
  'glass',
  'fronts',
  'and',
  'face',
  'inwards',
  'so',
  'privacy',
  'is',
  'not',
  'high',
  'on',
  'the',
  'agenda',
  'em',
  'city',
  'is',
  'home',
  'to',
  'manyaryans',
  'muslims',
  'gangstas',
  'latinos',
  'christians',
  'italians',
  'irish',
  'and',
  'moreso',
  'scuffles',
  'death',
  'stares',
  'dodgy',
  'dealings',
  'and',
  'shady',
  'agreements',
  'are',
  'never',
  'far',
  'awaybr',
  'br',
  'i',
  'would',
  'say',
  'the',
  'main',
  'appeal',
  'of',
  'the',
  'show',
  'is',
  'due',
  'to',
  'the',
  'fact',
  'that',
  'it',
  'goes',
  'where',
  'other',
  'shows',
  'wouldnt',
  'dare',
  'forget',
  'pretty',
  'pictures',
  'painted',
  'for',
  'mainstream',
  'audiences',
  'forget',
  'charm',
  'forget',
  'romanceoz',
  'doesnt',
  'mess',
  'around',
  'the',
  'first',
  'episode',
  'i',
  'ever',
  'saw',
  'struck',
  'me',
  'as',
  'so',
  'nasty',
  'it',
  'was',
  'surreal',
  'i',
  'couldnt',
  'say',
  'i',
  'was',
  'ready',
  'for',
  'it',
  'but',
  'as',
  'i',
  'watched',
  'more',
  'i',
  'developed',
  'a',
  'taste',
  'for',
  'oz',
  'and',
  'got',
  'accustomed',
  'to',
  'the',
  'high',
  'levels',
  'of',
  'graphic',
  'violence',
  'not',
  'just',
  'violence',
  'but',
  'injustice',
  'crooked',
  'guards',
  'wholl',
  'be',
  'sold',
  'out',
  'for',
  'a',
  'nickel',
  'inmates',
  'wholl',
  'kill',
  'on',
  'order',
  'and',
  'get',
  'away',
  'with',
  'it',
  'well',
  'mannered',
  'middle',
  'class',
  'inmates',
  'being',
  'turned',
  'into',
  'prison',
  'bitches',
  'due',
  'to',
  'their',
  'lack',
  'of',
  'street',
  'skills',
  'or',
  'prison',
  'experience',
  'watching',
  'oz',
  'you',
  'may',
  'become',
  'comfortable',
  'with',
  'what',
  'is',
  'uncomfortable',
  'viewingthats',
  'if',
  'you',
  'can',
  'get',
  'in',
  'touch',
  'with',
  'your',
  'darker',
  'side'],
 ['a',
  'wonderful',
  'little',
  'production',
  'br',
  'br',
  'the',
  'filming',
  'technique',
  'is',
  'very',
  'unassuming',
  'very',
  'oldtimebbc',
  'fashion',
  'and',
  'gives',
  'a',
  'comforting',
  'and',
  'sometimes',
  'discomforting',
  'sense',
  'of',
  'realism',
  'to',
  'the',
  'entire',
  'piece',
  'br',
  'br',
  'the',
  'actors',
  'are',
  'extremely',
  'well',
  'chosen',
  'michael',
  'sheen',
  'not',
  'only',
  'has',
  'got',
  'all',
  'the',
  'polari',
  'but',
  'he',
  'has',
  'all',
  'the',
  'voices',
  'down',
  'pat',
  'too',
  'you',
  'can',
  'truly',
  'see',
  'the',
  'seamless',
  'editing',
  'guided',
  'by',
  'the',
  'references',
  'to',
  'williams',
  'diary',
  'entries',
  'not',
  'only',
  'is',
  'it',
  'well',
  'worth',
  'the',
  'watching',
  'but',
  'it',
  'is',
  'a',
  'terrificly',
  'written',
  'and',
  'performed',
  'piece',
  'a',
  'masterful',
  'production',
  'about',
  'one',
  'of',
  'the',
  'great',
  'masters',
  'of',
  'comedy',
  'and',
  'his',
  'life',
  'br',
  'br',
  'the',
  'realism',
  'really',
  'comes',
  'home',
  'with',
  'the',
  'little',
  'things',
  'the',
  'fantasy',
  'of',
  'the',
  'guard',
  'which',
  'rather',
  'than',
  'use',
  'the',
  'traditional',
  'dream',
  'techniques',
  'remains',
  'solid',
  'then',
  'disappears',
  'it',
  'plays',
  'on',
  'our',
  'knowledge',
  'and',
  'our',
  'senses',
  'particularly',
  'with',
  'the',
  'scenes',
  'concerning',
  'orton',
  'and',
  'halliwell',
  'and',
  'the',
  'sets',
  'particularly',
  'of',
  'their',
  'flat',
  'with',
  'halliwells',
  'murals',
  'decorating',
  'every',
  'surface',
  'are',
  'terribly',
  'well',
  'done'],
 ['i',
  'thought',
  'this',
  'was',
  'a',
  'wonderful',
  'way',
  'to',
  'spend',
  'time',
  'on',
  'a',
  'too',
  'hot',
  'summer',
  'weekend',
  'sitting',
  'in',
  'the',
  'air',
  'conditioned',
  'theater',
  'and',
  'watching',
  'a',
  'lighthearted',
  'comedy',
  'the',
  'plot',
  'is',
  'simplistic',
  'but',
  'the',
  'dialogue',
  'is',
  'witty',
  'and',
  'the',
  'characters',
  'are',
  'likable',
  'even',
  'the',
  'well',
  'bread',
  'suspected',
  'serial',
  'killer',
  'while',
  'some',
  'may',
  'be',
  'disappointed',
  'when',
  'they',
  'realize',
  'this',
  'is',
  'not',
  'match',
  'point',
  '2',
  'risk',
  'addiction',
  'i',
  'thought',
  'it',
  'was',
  'proof',
  'that',
  'woody',
  'allen',
  'is',
  'still',
  'fully',
  'in',
  'control',
  'of',
  'the',
  'style',
  'many',
  'of',
  'us',
  'have',
  'grown',
  'to',
  'lovebr',
  'br',
  'this',
  'was',
  'the',
  'most',
  'id',
  'laughed',
  'at',
  'one',
  'of',
  'woodys',
  'comedies',
  'in',
  'years',
  'dare',
  'i',
  'say',
  'a',
  'decade',
  'while',
  'ive',
  'never',
  'been',
  'impressed',
  'with',
  'scarlet',
  'johanson',
  'in',
  'this',
  'she',
  'managed',
  'to',
  'tone',
  'down',
  'her',
  'sexy',
  'image',
  'and',
  'jumped',
  'right',
  'into',
  'a',
  'average',
  'but',
  'spirited',
  'young',
  'womanbr',
  'br',
  'this',
  'may',
  'not',
  'be',
  'the',
  'crown',
  'jewel',
  'of',
  'his',
  'career',
  'but',
  'it',
  'was',
  'wittier',
  'than',
  'devil',
  'wears',
  'prada',
  'and',
  'more',
  'interesting',
  'than',
  'superman',
  'a',
  'great',
  'comedy',
  'to',
  'go',
  'see',
  'with',
  'friends']]

Remove Stopwords

In [12]:
stop_words = set(stopwords.words('english'))
filter_tokens = []
for sentence in tokens:
    filtered = [word for word in sentence if word not in stop_words]
    filter_tokens.append(filtered)

Lemmatization

In [13]:
lemmatizer = WordNetLemmatizer()
lemmatizer_tokens = []
for sentence in filter_tokens:
    lemmatizer_tokens.append([lemmatizer.lemmatize(w) for w in sentence])
lemmatizer_tokens

[['one',
  'reviewer',
  'mentioned',
  'watching',
  '1',
  'oz',
  'episode',
  'youll',
  'hooked',
  'right',
  'exactly',
  'happened',
  'mebr',
  'br',
  'first',
  'thing',
  'struck',
  'oz',
  'brutality',
  'unflinching',
  'scene',
  'violence',
  'set',
  'right',
  'word',
  'go',
  'trust',
  'show',
  'faint',
  'hearted',
  'timid',
  'show',
  'pull',
  'punch',
  'regard',
  'drug',
  'sex',
  'violence',
  'hardcore',
  'classic',
  'use',
  'wordbr',
  'br',
  'called',
  'oz',
  'nickname',
  'given',
  'oswald',
  'maximum',
  'security',
  'state',
  'penitentary',
  'focus',
  'mainly',
  'emerald',
  'city',
  'experimental',
  'section',
  'prison',
  'cell',
  'glass',
  'front',
  'face',
  'inwards',
  'privacy',
  'high',
  'agenda',
  'em',
  'city',
  'home',
  'manyaryans',
  'muslim',
  'gangsta',
  'latino',
  'christian',
  'italian',
  'irish',
  'moreso',
  'scuffle',
  'death',
  'stare',
  'dodgy',
  'dealing',
  'shady',
  'agreement',
  'never',
  'far',
  'awaybr',
  'br',
  'would',
  'say',
  'main',
  'appeal',
  'show',
  'due',
  'fact',
  'go',
  'show',
  'wouldnt',
  'dare',
  'forget',
  'pretty',
  'picture',
  'painted',
  'mainstream',
  'audience',
  'forget',
  'charm',
  'forget',
  'romanceoz',
  'doesnt',
  'mess',
  'around',
  'first',
  'episode',
  'ever',
  'saw',
  'struck',
  'nasty',
  'surreal',
  'couldnt',
  'say',
  'ready',
  'watched',
  'developed',
  'taste',
  'oz',
  'got',
  'accustomed',
  'high',
  'level',
  'graphic',
  'violence',
  'violence',
  'injustice',
  'crooked',
  'guard',
  'wholl',
  'sold',
  'nickel',
  'inmate',
  'wholl',
  'kill',
  'order',
  'get',
  'away',
  'well',
  'mannered',
  'middle',
  'class',
  'inmate',
  'turned',
  'prison',
  'bitch',
  'due',
  'lack',
  'street',
  'skill',
  'prison',
  'experience',
  'watching',
  'oz',
  'may',
  'become',
  'comfortable',
  'uncomfortable',
  'viewingthats',
  'get',
  'touch',
  'darker',
  'side'],
 ['wonderful',
  'little',
  'production',
  'br',
  'br',
  'filming',
  'technique',
  'unassuming',
  'oldtimebbc',
  'fashion',
  'give',
  'comforting',
  'sometimes',
  'discomforting',
  'sense',
  'realism',
  'entire',
  'piece',
  'br',
  'br',
  'actor',
  'extremely',
  'well',
  'chosen',
  'michael',
  'sheen',
  'got',
  'polari',
  'voice',
  'pat',
  'truly',
  'see',
  'seamless',
  'editing',
  'guided',
  'reference',
  'williams',
  'diary',
  'entry',
  'well',
  'worth',
  'watching',
  'terrificly',
  'written',
  'performed',
  'piece',
  'masterful',
  'production',
  'one',
  'great',
  'master',
  'comedy',
  'life',
  'br',
  'br',
  'realism',
  'really',
  'come',
  'home',
  'little',
  'thing',
  'fantasy',
  'guard',
  'rather',
  'use',
  'traditional',
  'dream',
  'technique',
  'remains',
  'solid',
  'disappears',
  'play',
  'knowledge',
  'sens',
  'particularly',
  'scene',
  'concerning',
  'orton',
  'halliwell',
  'set',
  'particularly',
  'flat',
  'halliwells',
  'mural',
  'decorating',
  'every',
  'surface',
  'terribly',
  'well',
  'done'],
 ['thought',
  'wonderful',
  'way',
  'spend',
  'time',
  'hot',
  'summer',
  'weekend',
  'sitting',
  'air',
  'conditioned',
  'theater',
  'watching',
  'lighthearted',
  'comedy',
  'plot',
  'simplistic',
  'dialogue',
  'witty',
  'character',
  'likable',
  'even',
  'well',
  'bread',
  'suspected',
  'serial',
  'killer',
  'may',
  'disappointed',
  'realize',
  'match',
  'point',
  '2',
  'risk',
  'addiction',
  'thought',
  'proof',
  'woody',
  'allen',
  'still',
  'fully',
  'control',
  'style',
  'many',
  'u',
  'grown',
  'lovebr',
  'br',
  'id',
  'laughed',
  'one',
  'woodys',
  'comedy',
  'year',
  'dare',
  'say',
  'decade',
  'ive',
  'never',
  'impressed',
  'scarlet',
  'johanson',
  'managed',
  'tone',
  'sexy',
  'image',
  'jumped',
  'right',
  'average',
  'spirited',
  'young',
  'womanbr',
  'br',
  'may',
  'crown',
  'jewel',
  'career',
  'wittier',
  'devil',
  'wear',
  'prada',
  'interesting',
  'superman',
  'great',
  'comedy',
  'go',
  'see',
  'friend']]

Join back the tokens into cleaned texts.

In [14]:
clean_texts = [" ".join(sentence) for sentence in lemmatizer_tokens]
clean_texts

['one reviewer mentioned watching 1 oz episode youll hooked right exactly happened mebr br first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use wordbr br called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home manyaryans muslim gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far awaybr br would say main appeal show due fact go show wouldnt dare forget pretty picture painted mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high level graphic violence violence injustice crooked guard wholl sold nickel inmate wholl kill order get away well mannered middle class inmate turned prison bitch due lack street skill prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side',
 'wonderful little production br br filming technique unassuming oldtimebbc fashion give comforting sometimes discomforting sense realism entire piece br br actor extremely well chosen michael sheen got polari voice pat truly see seamless editing guided reference williams diary entry well worth watching terrificly written performed piece masterful production one great master comedy life br br realism really come home little thing fantasy guard rather use traditional dream technique remains solid disappears play knowledge sens particularly scene concerning orton halliwell set particularly flat halliwells mural decorating every surface terribly well done',
 'thought wonderful way spend time hot summer weekend sitting air conditioned theater watching lighthearted comedy plot simplistic dialogue witty character likable even well bread suspected serial killer may disappointed realize match point 2 risk addiction thought proof woody allen still fully control style many u grown lovebr br id laughed one woodys comedy year dare say decade ive never impressed scarlet johanson managed tone sexy image jumped right average spirited young womanbr br may crown jewel career wittier devil wear prada interesting superman great comedy go see friend']

Create One Function

In [15]:
def preprocess_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return " ".join(tokens)

Apply On Dataset

In [16]:
data["clean_text"] = data["review"].apply(preprocess_text)

data[["review","clean_text","sentiment"]].head()

,review,clean_text,sentiment
0,One of the other reviewers has mentioned that ...,one reviewer mentioned watching 1 oz episode y...,positive
1,A wonderful little production. <br /><br />The...,wonderful little production br br filming tech...,positive
2,I thought this was a wonderful way to spend ti...,thought wonderful way spend time hot summer we...,positive
3,Basically there's a family where a little boy ...,basically there family little boy jake think t...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter matteis love time money visually stunni...,positive

FEATURE ENGINEERING

In [17]:
X = data["clean_text"]
y = data["sentiment"]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Using Bag Of Words

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

Using TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
TFidf_vectorizer = TfidfVectorizer()
X_train_vector = TFidf_vectorizer.fit_transform(X_train)
X_test_vector = TFidf_vectorizer.transform(X_test)

MACHINE LEARNING MODELS

In [21]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train_vector, y_train)

nb_pred = nb_model.predict(X_test_vector)

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

Naive Bayes Accuracy: 0.8692

In [22]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_vector, y_train)

lr_pred = lr_model.predict(X_test_vector)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy: 0.8957

In [24]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(X_train_vector, y_train)

svm_pred = svm_model.predict(X_test_vector)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

SVM Accuracy: 0.8991

MODEL SAVING + PREDICTION PIPELINE

In [27]:
svm_model

LinearSVC()

In [28]:
best_model = svm_model

In [31]:
import joblib

joblib.dump(svm_model, "sentiment_model.joblib")
joblib.dump(TFidf_vectorizer, "tfidf_vectorizer.joblib")

['tfidf_vectorizer.joblib']

In [32]:
import os
os.listdir()

['.git',
 'aclImdb',
 'IMDB Dataset.csv',
 'main.ipynb',
 'main.py',
 'sentiment_model.joblib',
 'tfidf_vectorizer.joblib']

In [33]:
model = joblib.load("sentiment_model.joblib")
vectorizer = joblib.load("tfidf_vectorizer.joblib")

In [34]:
def predict_sentiment(text):
    clean = preprocess_text(text)
    vec = vectorizer.transform([clean])
    return model.predict(vec)[0]

In [35]:
predict_sentiment("This movie was fantastic")
predict_sentiment("Worst movie ever")

'negative'